### ISSUE TITLE
--trusted-ca-file support

### ISSUE THREAD

**Issue by nixwiz** [mylesw42/osc#2]
sensuctl supports --trusted-ca-file for verifying a certificate from a custom certificate authority.  Add support for doing this on a per cluster config basis in the event clusters use different CAs.

**Comment by mylesw42** [comment]
I've added support for trusted-ca-file as a config parameter in v0.2.0. The README is updated for usage. Let me know if this works for you.

**Comment by nixwiz** [comment]
It doesn't seem to be working.  The CA file works fine with `sensuctl configure`:

```
$ ./osc connect backend
Get "https://backend:8080/auth/test": x509: certificate signed by unknown authority
Auth failed! Check profile credentials.

$ grep trusted-ca-file ~/.config/osc.config.yaml
  trusted-ca-file: "/Users/todd/ssl/ca.pem"

$ sensuctl configure --trusted-ca-file /Users/todd/ssl/ca.pem
? Sensu Backend URL: https://backend:8080
? Username: admin
? Password: *********
? Namespace: default
? Preferred output format: tabular
```

**Comment by mylesw42** [comment]
I think I know what's happening. OSC doesn't use the pem when making the initial connection. It just writes the location in the config, provided it can auth against the backend. OSC does use the insecure-skip-tls-verify parameter. If you put that parameter as true, does it work? But then that means the insecure will be set to true in the config as it's written out. I may need to revisit.
